
blank_lines_upper_bound = 7
brace_style = "AlwaysNextLine"

disable_all_formatting = true

empty_item_single_line = true
enum_discrim_align_threshold = 0

fn_args_layout = "Tall"
fn_single_line = true # #3358

wrap_comments = true
